### ISSUE TITLE
Generación de Apis CRUD de solicitud

### ISSUE THREAD

**Issue by CrissUD** [udistrital/solicitudes_crud#1]

**Comment by mvcalderonc** [comment]
## Generación de api crud para el módulo de solicitudes
Se parte del modelo de datos aprobado por la oficina asesora de sistemas
![modelo_solicitud](https://user-images.githubusercontent.com/44048060/99477113-d9d0d900-291f-11eb-999b-e187cdd823f7.png)

con lo cual se genera un controlador y un modelo por cada una de la tablas existentes en el modelo de datos de la imagen anterior
![image](https://user-images.githubusercontent.com/44048060/99477279-2ddbbd80-2920-11eb-8f70-be8288ba33b5.png)

en dónde cada controlador contiene los métodos para las operaciones crud (Create, Read, Update y Delete) de cada tabla
![image](https://user-images.githubusercontent.com/44048060/99477708-0d603300-2921-11eb-8f3c-7657787db5f7.png)

y en cada modelo se muestran las propiedades de cada una de las tablas
![image](https://user-images.githubusercontent.com/44048060/99477742-21a43000-2921-11eb-8604-8a0882de17c3.png)

Se ejecuta la api de manera local
![image](https://user-images.githubusercontent.com/44048060/99477924-81024000-2921-11eb-9eed-ba36b28b3dc1.png)
![image](https://user-images.githubusercontent.com/44048060/99477984-9d05e180-2921-11eb-9a46-4f018f47c97b.png)

Se inserta un registro en la tabla de estados para realizar una verificación del funcionamiento del api
![image](https://user-images.githubusercontent.com/44048060/99478233-04bc2c80-2922-11eb-9d49-29565600c2b3.png)

Se realiza una prueba de consulta desde postman para verificar que esté consultando los datos en la base de datos
![image](https://user-images.githubusercontent.com/44048060/99478037-b27b0b80-2921-11eb-99ed-a0a9d3b85a0a.png)

**Comment by CrissUD** [comment]
- Actualización de id de dependencia en migraciones
- Generación de transacción para registro de solicitud
- Actualización de código para manejo de fechas
- Revisión de refractor de controladores
- Gestión de docker en el api

**Comment by EstefaniaPerezTorres** [comment]
crear transacción de evolución de estado de solicitudes.

**Comment by mvcalderonc** [comment]
# Generación de transacción para insertar y actualizar solicitudes

![image](https://user-images.githubusercontent.com/44048060/101200850-dbdfab00-3634-11eb-92ad-2b62ae315106.png)

Se generan los métodos
* POST
Reliza la inserción un una nueva solicitud para lo cual requiere de los siguientes elementos:
  * Solicitud
Contiene un objeto único de tipo Solicitud que se insertará.
  * Solicitantes
Contiene una lista de objetos de tipo Solicitante indicando los solicitantes que se relacionarán con la solicitud.
  * Observaciones
Contiene una lista de objetos de tipo Observacion con las observaciones que se relacionarán con la solicitud.
  * EvolucionesEstado
Contiene una lista de objetos de tipo SolicitudEvolucionEstado con las evoluciones de estados que se relacionarán con la solicitud.
* PUT
Realiza la actualización de una solicitud para lo cual requiere el identificador de la solicitud que se actualizará y los siguientes elementos:
  * Solicitud
Contiene un objeto único de tipo Solicitud que se actualizará.
  * Solicitantes
Contiene una lista de objetos de tipo Solicitante, sin embargo, no se procesará.
  * Observaciones
Contiene una lista de objetos de tipo Observacion con las observaciones que se relacionarán con la solicitud, si ya existe el registro se actualizará en caso contrario se insertará un nuevo.
  * EvolucionesEstado
Contiene una lista de objetos de tipo SolicitudEvolucionEstado con las evoluciones de estados que se relacionarán con la solicitud, si ya existe el registro se actualizará en caso contrario se insertará un nuevo.
* GetAll
Realiza la consulta de todas las solicitudes.
* GetAllByPersona
Realiza la consulta de solicitudes buscando por aquellas que tengan relacionado un tercero.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
