### ISSUE TITLE
Realizar Lógica de flujo para solicitudes tipo evaluación

### ISSUE THREAD

**Issue by CrissUD** [udistrital/solicitudes_crud#34]

**Comment by CrissUD** [comment]
# Generación de Solicitudes tipo evaluación

## Migration de información
Primero se realiza una migración en la cual va insertada la nueva información del tipo de solicitud para evaluación que involucra inserts en las tablas **tipo_solicitud, estado, estado_tipo_solicitud**:
![inserts](https://user-images.githubusercontent.com/44172561/103545525-b205e800-4e6f-11eb-804e-3f1aec67e654.png)


## Lógica de generación Cliente

Dentro del cliente se crea lógica para generar solicitudes tipo evaluación una ves se realiza el envío de una invitación a un par externo:
![image](https://user-images.githubusercontent.com/44172561/103546177-951de480-4e70-11eb-8821-3e78eeab3129.png)

El envío de invitación además de generar un cambio de estado, el envío de notificación por correo también generará la creación de una solicitud tipo evaluación:
![generacionSolicitudCliente](https://user-images.githubusercontent.com/44172561/103546410-f0e86d80-4e70-11eb-939b-ce3ef02cf919.png)

Se puede observar que para la generación de la solicitud hija se reutiliza el método post de la transacción que se usa para generar solicitudes docente.

**Comment by CrissUD** [comment]
# Listado de solicitudes por aceptar de un par externo

Una vez el par externo pase por el flujo de **inscripción de par externo con su respectiva información complementaria** podrá  revisar el listado de invitaciones que tiene pendientes por aceptar, estas invitaciones se filtran a través del correo electrónico que se registró al momento de enviar la invitación:
![filter](https://user-images.githubusercontent.com/44172561/103547417-60ab2800-4e72-11eb-9f37-9b2d38830495.png)

El listado en el cliente se verá de la siguiente manera:
![image](https://user-images.githubusercontent.com/44172561/103547592-9c45f200-4e72-11eb-879d-312635eb2251.png)

Una vez el par externo de click en el botón aceptar, saldrá una opción de confirmación:
![image](https://user-images.githubusercontent.com/44172561/103547831-e929c880-4e72-11eb-8c2d-30ea460c3fd7.png)

Una vez la solicitud sea aceptada, se registrará el par externo como un solicitante de la solicitud de evaluación, seguido se cambiará el estado de la solicitud de evaluación a "en evaluación".
![aceptacionInvitacion](https://user-images.githubusercontent.com/44172561/103548404-c1873000-4e73-11eb-8da8-13f96654505f.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
