### ISSUE TITLE
Lógica para termino de flujo de solicitudes y separación de solicitudes activas e inactivas

### ISSUE THREAD

**Issue by CrissUD** [udistrital/solicitudes_crud#45]

**Comment by CrissUD** [comment]
# Generación de estado en solicitudes y separación de solicitudes activas e inactivas:

Para generar el proceso de fin de flujo de las solicitudes que hayan sido tratadas en el comité y hayan sido aceptadas en el acta, se cree conveniente tener un atributo que se encargue de indicar si una solicitud esta activa en el flujo de aceptación o si esta ya ha pasado por dicho ciclo, para esto se crea un nuevo atributo en la tabla solicitudes llamada **solicitud_finalizada** de tipo boolean que por defecto va a generar el campo en false indicando que sigue en su curso, para esto se realiza una migración con el siguiente sql:
![image](https://user-images.githubusercontent.com/44172561/105503114-317b2000-5c94-11eb-808d-e948dec6e842.png)
También se genera atributo dentro del modelo:
![solicitud](https://user-images.githubusercontent.com/44172561/105503440-9171c680-5c94-11eb-8a86-2d4e946dfeb1.png)

##  Logica en Solicitudes_CRUD

Una vez se crea este nuevo atributo se procede a crear nuevos métodos en los controladores que se encarguen de enviar solicitudes filtradas por este nuevo campo:

### Metodos get en el controlador de Solicitudes_crud
* Métodos get para traer solicitudes activas:
![solicitudes activas](https://user-images.githubusercontent.com/44172561/105503657-dc8bd980-5c94-11eb-93fe-7d0129942a10.png)
* Métodos get para traer solicitudes inactivas:
![solicitudes inactivas](https://user-images.githubusercontent.com/44172561/105503690-e6add800-5c94-11eb-8ff2-ec14e34aa86e.png)

### Metodos get en el modelo de Solicitudes_crud
![modelo solicitudes filtro](https://user-images.githubusercontent.com/44172561/105503915-2674bf80-5c95-11eb-9dbd-27f5425e39c6.png)

## Lógica en SGA_MID

Así mismo en sga_mid se generan métodos get en el controlador para traer la información de forma filtrada:
### Metodos get en el controlador de Sga_Mid
* Métodos get para traer todas las solicitudes activas o inactivas:
![sga controlador all solicitudes](https://user-images.githubusercontent.com/44172561/105504732-1e694f80-5c96-11eb-9cd0-bd550d2125b8.png)
* Métodos get para traer las solicitudes de un tercero activas o inactivas:
![sga controlador tercero solicitudes](https://user-images.githubusercontent.com/44172561/105504898-4b1d6700-5c96-11eb-9e6b-b831665ae56d.png)

### Metodos get en el modelo de Sga_Mid

En cuanto a los modelos del Sga_mid se crea una logica para crear el endpoint y asi utilizar los mismos metodos existentes sin crear nuevos:

![endpoint all](https://user-images.githubusercontent.com/44172561/105505152-9cc5f180-5c96-11eb-8c78-820e4e496036.png)
![endpoint tercero](https://user-images.githubusercontent.com/44172561/105505180-a3546900-5c96-11eb-8f1a-eb9add7df6ed.png)

**Comment by CrissUD** [comment]
# Generación estado de paquetes

Al mostrar el listado de paquetes este trae un estado que se estaba verificando a través del atributo **Activo**, sin embargo se opta por crear un nuevo atributo que indica el estado del paquete llamado **paquete_revisado** y que será un booleano que por defecto estara en false indicando que un paquete creado aun no ha sido revisado, esto se realiza a través de una migracion con el siguiente sql:
![image](https://user-images.githubusercontent.com/44172561/105505549-13fb8580-5c97-11eb-907f-a449cff8ba9d.png)

De igual forma se agrega atributo al modelo de paquete:
![paquete](https://user-images.githubusercontent.com/44172561/105505654-368d9e80-5c97-11eb-93fc-e5bafa582a37.png)


De esta forma en el cliente se podrá validar el estado del paquete en general con este nuevo atributo:
![image](https://user-images.githubusercontent.com/44172561/105507234-f2030280-5c98-11eb-91a2-1377949eed6c.png)

**Comment by CrissUD** [comment]
# Lógica para cambio de estado en cliente

Una vez en el cliente se de click en el botón de aceptar acta lo primero que se hará es un filtrado de las solicitudes a enviar para excluir aquellas que han sido aplazadas, de igual forma se cambia el estado de la solicitud para indicar que la solicitud ya ha sido finalizada: 
![acceptCertificate](https://user-images.githubusercontent.com/44172561/105508305-3b078680-5c9a-11eb-99d5-b786290eeb32.png)

Asi mismo en el sga mid se agrega una logica adicional en la actualizacion de paquetes para que tenga en cuenta los casos en los que pueden cambiar los estados de una solicitud o de un paquete: 
![put paquete](https://user-images.githubusercontent.com/44172561/105508588-8ae64d80-5c9a-11eb-8edc-6f98f425a5e7.png)


Finalmente en solicitudes CRUD también se tienen en cuenta estos nuevos atributos para su modificación
![paqueterevisado](https://user-images.githubusercontent.com/44172561/105508883-e9abc700-5c9a-11eb-8ac4-bdbca23eff62.png)

![solicitudfinalizada](https://user-images.githubusercontent.com/44172561/105508922-f3352f00-5c9a-11eb-840e-c352726f6de5.png)

**Comment by CrissUD** [comment]
# Listado de solicitudes Inactivas

En el cliente se crea una nueva opcion en el menu donde se podrán revisar las solicitudes que ya han cumplido su ciclo:

![image](https://user-images.githubusercontent.com/44172561/105509110-2ecff900-5c9b-11eb-8536-b725b34c9974.png)


En esta opción del menú se reutiliza el componente **list-producción_academica** y para poder realizar el filtro de separación se utiliza el servicio de **Active Routing**  esto quiere decir que por url enviara el esrado y gracias a la toma de este se realiza el filtrado: 
![image](https://user-images.githubusercontent.com/44172561/105509382-6e96e080-5c9b-11eb-83e0-4ffe3693b875.png)
![image](https://user-images.githubusercontent.com/44172561/105509511-91c19000-5c9b-11eb-96a4-2c909f21b9ef.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
